version: '3'
services:
    client:
      container_name: 'portfolio'
      environment:
        - REACT_APP_SERVER_URL=https://portserver.anurags.tech
      build:
        dockerfile: Dockerfile.prod
        context: ./portfolio/
