version: '3'
services:
    client:
      image: theanuragshukla/portfolio-v2
      ports:
        - 3001:80
      links:
          - server


    server:
      container_name: 'portserver'
      build:
        args:
          JWT_SECRET: ${JWT_SECRET}
          ADMIN_SECRET: ${ADMIN_SECRET}
          MONGO_URL: ${MONGO_URL}
          CLIENT_URL: client
        dockerfile: Dockerfile
        context: ./server/
      ports:
        - 5000:8000
      env_file: .env
