FROM node:18-alpine AS builder
ARG REACT_APP_SERVER_URL

ENV NODE_ENV production
ENV REACT_APP_SERVER_URL $REACT_APP_SERVER_URL

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install --production

COPY . .

RUN npm run build

FROM nginx:1.25.3-alpine as production
ENV NODE_ENV production

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=builder /app/build .
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
