FROM node:18-alpine AS development
ARG REACT_APP_SERVER_URL

ENV NODE_ENV development
ENV REACT_APP_SERVER_URL $REACT_APP_SERVER_URL

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

EXPOSE 3000

CMD [ "npm", "start" ]
